/**
 * Builds a comprehensive plain-text analysis report from all available analyses.
 * @param {object} state - ResumeContext state
 * @returns {string} Full report text
 */
export function buildAnalysisReport(state) {
  const { fileName, analyses } = state;
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const time = new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

  const W = 62;
  const box  = (char = '═') => char.repeat(W);
  const div  = () => '─'.repeat(W);
  const mid  = (text, char = '═') => {
    const pad = Math.max(0, W - text.length - 2);
    const l = Math.floor(pad / 2);
    const r = pad - l;
    return `${char.repeat(l)} ${text} ${char.repeat(r)}`;
  };
  const line  = (label, value) => `  ${label.padEnd(28)} ${value}`;
  const bullet = (text, sym = '•') => `  ${sym}  ${text}`;
  const nl    = () => '';

  const lines = [];

  // ── Cover page ────────────────────────────────────────────────
  lines.push(box());
  lines.push(mid('AI RESUME ANALYSIS REPORT'));
  lines.push(box());
  lines.push(nl());
  lines.push(line('Resume File:', fileName || 'Unknown'));
  lines.push(line('Generated On:', `${date} at ${time}`));
  lines.push(line('Generated By:', 'AI Resume Analyzer'));
  lines.push(nl());

  // Quick score summary if available
  const ats   = analyses.ats?.overallScore;
  const grammar = analyses.grammar?.overallScore;
  const match = analyses.jobMatch?.matchPercentage;
  const skillMatch = analyses.skills?.matchPercentage;

  if (ats !== undefined || grammar !== undefined || match !== undefined) {
    lines.push(div());
    lines.push('  SCORE SUMMARY');
    lines.push(div());
    if (ats       !== undefined) lines.push(line('ATS Score:',          `${ats}/100   ${scoreLabel(ats)}`));
    if (grammar   !== undefined) lines.push(line('Writing Score:',      `${grammar}/100   ${scoreLabel(grammar)}`));
    if (match     !== undefined) lines.push(line('Job Match:',          `${match}%   ${scoreLabel(match)}`));
    if (skillMatch !== undefined) lines.push(line('Skill Match:',       `${skillMatch}%`));
    lines.push(nl());
  }

  // ── 1. ATS Analysis ──────────────────────────────────────────
  if (analyses.ats) {
    const d = analyses.ats;
    lines.push(box('═'));
    lines.push(mid('1. ATS SCORE ANALYSIS'));
    lines.push(box('═'));
    lines.push(nl());
    lines.push(line('Overall ATS Score:', `${d.overallScore}/100 — ${scoreLabel(d.overallScore)}`));
    lines.push(nl());

    if (d.sections) {
      lines.push('  SECTION BREAKDOWN');
      lines.push(div());
      Object.entries(d.sections).forEach(([key, sec]) => {
        const label = key.replace(/([A-Z])/g, ' $1').trim();
        const status = sec.found ? '✓' : '✗';
        lines.push(`  ${status}  ${label.padEnd(22)} ${sec.score}/${sec.maxScore}`);
        if (sec.details) lines.push(`       ${sec.details}`);
      });
      lines.push(nl());
    }

    if (d.strengths?.length) {
      lines.push('  STRENGTHS');
      lines.push(div());
      d.strengths.forEach(s => lines.push(bullet(s, '✓')));
      lines.push(nl());
    }

    if (d.weaknesses?.length) {
      lines.push('  WEAKNESSES');
      lines.push(div());
      d.weaknesses.forEach(w => lines.push(bullet(w, '✗')));
      lines.push(nl());
    }

    if (d.missingElements?.length) {
      lines.push('  MISSING ELEMENTS');
      lines.push(div());
      d.missingElements.forEach(m => lines.push(bullet(m, '△')));
      lines.push(nl());
    }

    if (d.atsKeywords?.length) {
      lines.push('  ATS KEYWORDS DETECTED');
      lines.push(div());
      lines.push(`  ${d.atsKeywords.join(', ')}`);
      lines.push(nl());
    }
  }

  // ── 2. Grammar & Writing ─────────────────────────────────────
  if (analyses.grammar) {
    const d = analyses.grammar;
    lines.push(box('═'));
    lines.push(mid('2. GRAMMAR & WRITING ANALYSIS'));
    lines.push(box('═'));
    lines.push(nl());
    lines.push(line('Writing Score:',       `${d.overallScore}/100`));
    lines.push(line('Professionalism:',     `${d.professionalismScore}/100`));
    lines.push(line('Total Issues Found:',  `${(d.issues || []).length}`));
    lines.push(nl());

    if (d.weakActionVerbs?.length) {
      lines.push('  WEAK ACTION VERBS TO REPLACE');
      lines.push(div());
      lines.push(`  ${d.weakActionVerbs.join(', ')}`);
      lines.push(nl());
    }

    if (d.strongerAlternatives && Object.keys(d.strongerAlternatives).length) {
      lines.push('  STRONGER ALTERNATIVES');
      lines.push(div());
      Object.entries(d.strongerAlternatives).slice(0, 8).forEach(([weak, strong]) => {
        lines.push(`  ${weak.padEnd(18)} →  ${(strong || []).join(', ')}`);
      });
      lines.push(nl());
    }

    if (d.issues?.length) {
      lines.push('  ISSUES FOUND');
      lines.push(div());
      d.issues.slice(0, 15).forEach((issue, i) => {
        lines.push(`  [${i + 1}] Type: ${issue.type?.toUpperCase() || 'ISSUE'}`);
        lines.push(`      Original:   ${issue.original}`);
        lines.push(`      Suggestion: ${issue.suggestion}`);
        if (issue.explanation) lines.push(`      Why:        ${issue.explanation}`);
        lines.push(nl());
      });
    }

    if (d.writingTips?.length) {
      lines.push('  WRITING TIPS');
      lines.push(div());
      d.writingTips.forEach(t => lines.push(bullet(t)));
      lines.push(nl());
    }
  }

  // ── 3. Skill Gap Analysis ─────────────────────────────────────
  if (analyses.skills) {
    const d = analyses.skills;
    lines.push(box('═'));
    lines.push(mid('3. SKILL GAP ANALYSIS'));
    lines.push(box('═'));
    lines.push(nl());
    lines.push(line('Target Role:',    d.jobRole || 'Not specified'));
    lines.push(line('Skill Match:',    `${d.matchPercentage}%`));
    lines.push(line('Skills Found:',   `${d.foundSkills?.length || 0}`));
    lines.push(line('Skills Missing:', `${d.missingSkills?.length || 0}`));
    lines.push(nl());

    if (d.foundSkills?.length) {
      lines.push('  SKILLS YOU HAVE  ✓');
      lines.push(div());
      lines.push(`  ${d.foundSkills.join(', ')}`);
      lines.push(nl());
    }

    if (d.missingSkills?.length) {
      lines.push('  SKILLS TO LEARN  ✗');
      lines.push(div());
      lines.push(`  ${d.missingSkills.join(', ')}`);
      lines.push(nl());
    }

    if (d.niceToHaveSkills?.length) {
      lines.push('  NICE-TO-HAVE SKILLS');
      lines.push(div());
      lines.push(`  ${d.niceToHaveSkills.join(', ')}`);
      lines.push(nl());
    }

    if (d.skillsByCategory) {
      lines.push('  SKILLS BY CATEGORY');
      lines.push(div());
      Object.entries(d.skillsByCategory).forEach(([cat, skills]) => {
        lines.push(`  ${cat.toUpperCase()}`);
        if (skills.found?.length)   lines.push(`    Have:    ${skills.found.join(', ')}`);
        if (skills.missing?.length) lines.push(`    Missing: ${skills.missing.join(', ')}`);
      });
      lines.push(nl());
    }

    if (d.courseSuggestions?.length) {
      lines.push('  RECOMMENDED COURSES');
      lines.push(div());
      d.courseSuggestions.forEach(c => {
        lines.push(`  • ${c.skill} → "${c.course}" on ${c.platform}`);
      });
      lines.push(nl());
    }
  }

  // ── 4. Improvement Suggestions ────────────────────────────────
  if (analyses.improvements) {
    const d = analyses.improvements;
    lines.push(box('═'));
    lines.push(mid('4. IMPROVEMENT SUGGESTIONS'));
    lines.push(box('═'));
    lines.push(nl());
    lines.push(line('Total Suggestions:', `${d.totalSuggestions}`));
    lines.push(nl());

    if (d.missingSections?.length) {
      lines.push('  MISSING SECTIONS');
      lines.push(div());
      lines.push(`  ${d.missingSections.join(', ')}`);
      lines.push(nl());
    }

    if (d.atsKeywordsToAdd?.length) {
      lines.push('  ATS KEYWORDS TO ADD');
      lines.push(div());
      lines.push(`  ${d.atsKeywordsToAdd.join(', ')}`);
      lines.push(nl());
    }

    if (d.prioritySuggestions?.length) {
      lines.push('  PRIORITY SUGGESTIONS');
      lines.push(div());
      ['high', 'medium', 'low'].forEach(priority => {
        const group = d.prioritySuggestions.filter(s => s.priority === priority);
        if (!group.length) return;
        lines.push(`  [${priority.toUpperCase()} PRIORITY]`);
        group.forEach(s => {
          lines.push(`  Section: ${s.section}`);
          lines.push(`  Issue:   ${s.issue}`);
          lines.push(`  Fix:     ${s.suggestion}`);
          lines.push(nl());
        });
      });
    }

    if (d.bulletPointImprovements?.length) {
      lines.push('  BULLET POINT REWRITES');
      lines.push(div());
      d.bulletPointImprovements.forEach((b, i) => {
        lines.push(`  [${i + 1}] Before: ${b.original}`);
        lines.push(`       After:  ${b.improved}`);
        if (b.reason) lines.push(`       Why:    ${b.reason}`);
        lines.push(nl());
      });
    }

    if (d.overallTips?.length) {
      lines.push('  GENERAL TIPS');
      lines.push(div());
      d.overallTips.forEach(t => lines.push(bullet(t)));
      lines.push(nl());
    }
  }

  // ── 5. Job Match Analysis ─────────────────────────────────────
  if (analyses.jobMatch) {
    const d = analyses.jobMatch;
    lines.push(box('═'));
    lines.push(mid('5. JOB MATCH ANALYSIS'));
    lines.push(box('═'));
    lines.push(nl());
    lines.push(line('Match Percentage:',  `${d.matchPercentage}%`));
    lines.push(line('Match Level:',       d.matchLevel || '—'));
    lines.push(line('Matching Keywords:', `${d.matchingKeywords?.length || 0}`));
    lines.push(line('Missing Keywords:',  `${d.missingKeywords?.length || 0}`));
    lines.push(nl());

    if (d.experienceMatch) {
      lines.push(line('Experience Match:', `${d.experienceMatch.score}%  —  ${d.experienceMatch.notes}`));
    }
    if (d.educationMatch) {
      lines.push(line('Education Match:', `${d.educationMatch.score}%  —  ${d.educationMatch.notes}`));
    }
    lines.push(nl());

    if (d.matchingKeywords?.length) {
      lines.push('  MATCHING KEYWORDS  ✓');
      lines.push(div());
      lines.push(`  ${d.matchingKeywords.join(', ')}`);
      lines.push(nl());
    }

    if (d.missingKeywords?.length) {
      lines.push('  MISSING KEYWORDS  ✗');
      lines.push(div());
      lines.push(`  ${d.missingKeywords.join(', ')}`);
      lines.push(nl());
    }

    if (d.recommendations?.length) {
      lines.push('  RECOMMENDATIONS');
      lines.push(div());
      d.recommendations.forEach(r => lines.push(bullet(r)));
      lines.push(nl());
    }

    if (d.tailoringTips?.length) {
      lines.push('  HOW TO TAILOR YOUR RESUME');
      lines.push(div());
      d.tailoringTips.forEach(t => lines.push(bullet(t)));
      lines.push(nl());
    }
  }

  // ── 6. AI Rewrite Summary ─────────────────────────────────────
  if (analyses.rewrite) {
    const d = analyses.rewrite;
    lines.push(box('═'));
    lines.push(mid('6. AI REWRITE SUMMARY'));
    lines.push(box('═'));
    lines.push(nl());

    if (d.beforeAfterScore) {
      lines.push(line('Score Before Rewrite:', `${d.beforeAfterScore.before}/100`));
      lines.push(line('Score After Rewrite:',  `${d.beforeAfterScore.after}/100`));
      lines.push(line('Improvement:',          `+${d.beforeAfterScore.after - d.beforeAfterScore.before} points`));
      lines.push(nl());
    }

    if (d.improvedSummary) {
      lines.push('  REWRITTEN SUMMARY');
      lines.push(div());
      lines.push(`  ${d.improvedSummary}`);
      lines.push(nl());
    }

    if (d.keyImprovements?.length) {
      lines.push('  KEY IMPROVEMENTS MADE');
      lines.push(div());
      d.keyImprovements.forEach(i => lines.push(bullet(i, '✓')));
      lines.push(nl());
    }

    if (d.improvedBulletPoints?.length) {
      lines.push('  REWRITTEN BULLET POINTS');
      lines.push(div());
      d.improvedBulletPoints.forEach((b, i) => {
        lines.push(`  [${i + 1}] Before: ${b.original}`);
        lines.push(`       After:  ${b.improved}`);
        lines.push(nl());
      });
    }
  }

  // ── 7. Cover Letter ───────────────────────────────────────────
  if (analyses.coverLetter) {
    const d = analyses.coverLetter;
    lines.push(box('═'));
    lines.push(mid('7. GENERATED COVER LETTER'));
    lines.push(box('═'));
    lines.push(nl());
    if (d.coverLetter) {
      d.coverLetter.split('\n').forEach(l => lines.push(l ? `  ${l}` : nl()));
    }
    lines.push(nl());
  }

  // ── 8. Interview Questions ────────────────────────────────────
  if (analyses.interview) {
    const d = analyses.interview;
    lines.push(box('═'));
    lines.push(mid('8. INTERVIEW PREPARATION'));
    lines.push(box('═'));
    lines.push(nl());

    const sections = [
      { key: 'technicalQuestions',  label: 'TECHNICAL QUESTIONS' },
      { key: 'behavioralQuestions', label: 'BEHAVIORAL QUESTIONS' },
      { key: 'projectQuestions',    label: 'PROJECT QUESTIONS' },
      { key: 'hrQuestions',         label: 'HR / CULTURE QUESTIONS' },
    ];

    sections.forEach(({ key, label }) => {
      const qs = d[key];
      if (!qs?.length) return;
      lines.push(`  ${label}`);
      lines.push(div());
      qs.forEach((q, i) => {
        lines.push(`  Q${i + 1}: ${q.question}`);
        if (q.difficulty) lines.push(`       Difficulty: ${q.difficulty}`);
        if (q.topic)      lines.push(`       Topic: ${q.topic}`);
        if (q.competency) lines.push(`       Competency: ${q.competency}`);
        if (q.hint)       lines.push(`       Hint: ${q.hint}`);
        lines.push(nl());
      });
    });

    if (d.preparationTips?.length) {
      lines.push('  PREPARATION TIPS');
      lines.push(div());
      d.preparationTips.forEach(t => lines.push(bullet(t)));
      lines.push(nl());
    }
  }

  // ── Footer ────────────────────────────────────────────────────
  lines.push(box('═'));
  lines.push(mid('END OF REPORT'));
  lines.push(box('═'));
  lines.push(nl());
  lines.push(`  This report was generated by AI Resume Analyzer on ${date}.`);
  lines.push(`  Results are AI-generated and should be used as guidance only.`);
  lines.push(nl());

  return lines.join('\n');
}

/**
 * Trigger a PDF download of the full analysis report using jsPDF
 */
export async function downloadReport(state) {
  const { jsPDF } = await import('jspdf');

  const baseName = state.fileName?.replace(/\.[^/.]+$/, '') || 'resume';
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const time = new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
  const { analyses, fileName } = state;

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  // ── Page dimensions ──────────────────────────────────────────
  const PW = 210; // A4 width mm
  const PH = 297; // A4 height mm
  const ML = 15;  // margin left
  const MR = 15;  // margin right
  const TW = PW - ML - MR; // text width
  const MT = 15;  // margin top
  const MB = 15;  // margin bottom

  // ── Colors ────────────────────────────────────────────────────
  const C = {
    primary:   [79,  70,  229],  // indigo-600
    purple:    [124, 58,  237],  // violet-600
    dark:      [15,  23,  42 ],  // slate-900
    heading:   [30,  41,  59 ],  // slate-800
    body:      [71,  85,  105],  // slate-500
    muted:     [148, 163, 184],  // slate-400
    white:     [255, 255, 255],
    green:     [16,  185, 129],  // emerald-500
    amber:     [245, 158, 11 ],  // amber-500
    red:       [239, 68,  68 ],  // red-500
    bgLight:   [248, 250, 252],  // slate-50
    border:    [226, 232, 240],  // slate-200
    headerBg:  [79,  70,  229],  // indigo for section headers
  };

  let y = MT;
  let pageNum = 1;

  // ── Helpers ───────────────────────────────────────────────────

  const setFont = (style = 'normal', size = 10, color = C.body) => {
    doc.setFont('helvetica', style);
    doc.setFontSize(size);
    doc.setTextColor(...color);
  };

  const checkPage = (needed = 10) => {
    if (y + needed > PH - MB) {
      doc.addPage();
      pageNum++;
      y = MT;
      drawPageFooter();
    }
  };

  const drawPageFooter = () => {
    const saved = y;
    doc.setDrawColor(...C.border);
    doc.setLineWidth(0.3);
    doc.line(ML, PH - 10, PW - MR, PH - 10);
    setFont('normal', 8, C.muted);
    doc.text('AI Resume Analyzer — Confidential Report', ML, PH - 6);
    doc.text(`Page ${pageNum}`, PW - MR, PH - 6, { align: 'right' });
    y = saved;
  };

  const nl = (h = 5) => { y += h; };

  const drawHR = (color = C.border, w = 0.3) => {
    checkPage(4);
    doc.setDrawColor(...color);
    doc.setLineWidth(w);
    doc.line(ML, y, PW - MR, y);
    y += 3;
  };

  const drawText = (text, x, opts = {}) => {
    const { size = 10, style = 'normal', color = C.body, align = 'left', maxWidth } = opts;
    setFont(style, size, color);
    const lines = maxWidth ? doc.splitTextToSize(text, maxWidth) : [text];
    lines.forEach(line => {
      checkPage(size * 0.4 + 2);
      doc.text(line, x, y, { align });
      y += size * 0.4 + 1.5;
    });
  };

  const drawSectionHeader = (title, icon = '') => {
    checkPage(16);
    nl(4);
    // Background pill
    doc.setFillColor(...C.primary);
    doc.roundedRect(ML, y - 5, TW, 10, 2, 2, 'F');
    setFont('bold', 11, C.white);
    doc.text(`${icon}  ${title}`, ML + 4, y + 1.5);
    y += 8;
    nl(3);
  };

  const drawSubHeader = (title) => {
    checkPage(10);
    nl(2);
    setFont('bold', 9, C.heading);
    doc.text(title.toUpperCase(), ML, y);
    y += 4;
    doc.setDrawColor(...C.primary);
    doc.setLineWidth(0.5);
    doc.line(ML, y, ML + 40, y);
    y += 3;
  };

  const drawKeyValue = (label, value, valueColor = C.body) => {
    checkPage(7);
    setFont('bold', 9, C.heading);
    doc.text(label, ML, y);
    setFont('normal', 9, valueColor);
    doc.text(String(value), ML + 55, y);
    y += 5.5;
  };

  const drawBullet = (text, color = C.primary, indent = 0) => {
    checkPage(6);
    doc.setFillColor(...color);
    doc.circle(ML + indent + 1.5, y - 1, 1, 'F');
    setFont('normal', 9, C.body);
    const wrapped = doc.splitTextToSize(text, TW - indent - 6);
    wrapped.forEach((line, i) => {
      if (i > 0) checkPage(5);
      doc.text(line, ML + indent + 5, y);
      y += 4.5;
    });
  };

  const drawChip = (text, bg, textColor = C.white) => {
    const w = doc.getTextWidth(text) + 6;
    doc.setFillColor(...bg);
    doc.roundedRect(ML + (currentChipX || 0), y - 3.5, w, 5.5, 1.5, 1.5, 'F');
    setFont('bold', 8, textColor);
    doc.text(text, ML + (currentChipX || 0) + 3, y);
    currentChipX = (currentChipX || 0) + w + 3;
  };

  let currentChipX = 0;

  const drawChips = (items, bg, textColor = C.white) => {
    if (!items?.length) return;
    checkPage(8);
    currentChipX = 0;
    const lineH = 7;
    items.forEach(item => {
      const w = doc.getTextWidth(item) + 6;
      if (ML + currentChipX + w > PW - MR) {
        y += lineH;
        currentChipX = 0;
        checkPage(lineH);
      }
      drawChip(item, bg, textColor);
    });
    y += lineH;
    currentChipX = 0;
  };

  const drawScoreBar = (label, score, max = 100) => {
    checkPage(10);
    const pct = Math.min(score / max, 1);
    const barW = TW - 50;
    const barH = 3;
    const barX = ML + 40;
    const barColor = pct >= 0.75 ? C.green : pct >= 0.5 ? C.amber : C.red;

    setFont('normal', 9, C.heading);
    doc.text(label, ML, y);
    setFont('bold', 9, barColor);
    doc.text(`${score}/${max}`, PW - MR, y, { align: 'right' });

    y += 2;
    doc.setFillColor(...C.border);
    doc.roundedRect(barX, y - 1, barW, barH, 1, 1, 'F');
    doc.setFillColor(...barColor);
    doc.roundedRect(barX, y - 1, barW * pct, barH, 1, 1, 'F');
    y += 6;
  };

  const drawBeforeAfter = (before, after) => {
    checkPage(24);
    const colW = (TW - 6) / 2;

    // Before box
    doc.setFillColor(254, 242, 242);
    doc.setDrawColor(252, 165, 165);
    doc.setLineWidth(0.3);
    doc.roundedRect(ML, y, colW, 18, 2, 2, 'FD');
    setFont('bold', 7, C.red);
    doc.text('BEFORE', ML + 3, y + 5);
    setFont('normal', 8, C.body);
    const bLines = doc.splitTextToSize(before, colW - 6);
    bLines.slice(0, 3).forEach((l, i) => doc.text(l, ML + 3, y + 9 + i * 3.5));

    // After box
    const ax = ML + colW + 6;
    doc.setFillColor(240, 253, 244);
    doc.setDrawColor(134, 239, 172);
    doc.roundedRect(ax, y, colW, 18, 2, 2, 'FD');
    setFont('bold', 7, C.green);
    doc.text('AFTER', ax + 3, y + 5);
    setFont('normal', 8, C.body);
    const aLines = doc.splitTextToSize(after, colW - 6);
    aLines.slice(0, 3).forEach((l, i) => doc.text(l, ax + 3, y + 9 + i * 3.5));

    y += 22;
  };

  // ── COVER PAGE ────────────────────────────────────────────────
  // Gradient header block
  doc.setFillColor(...C.primary);
  doc.rect(0, 0, PW, 55, 'F');
  doc.setFillColor(...C.purple);
  doc.triangle(PW - 60, 0, PW, 0, PW, 55, 'F');

  setFont('bold', 22, C.white);
  doc.text('AI Resume Analysis', ML, 22);
  setFont('bold', 22, [199, 210, 254]);
  doc.text('Report', ML, 34);

  setFont('normal', 10, [199, 210, 254]);
  doc.text(`Generated: ${date} at ${time}`, ML, 44);

  y = 65;

  // File info card
  doc.setFillColor(...C.bgLight);
  doc.setDrawColor(...C.border);
  doc.setLineWidth(0.3);
  doc.roundedRect(ML, y, TW, 28, 3, 3, 'FD');
  setFont('bold', 10, C.heading);
  doc.text('Resume File', ML + 5, y + 8);
  setFont('normal', 10, C.body);
  doc.text(fileName || 'Unknown', ML + 5, y + 15);
  setFont('normal', 9, C.muted);
  doc.text(`Analyzed by AI Resume Analyzer`, ML + 5, y + 22);
  y += 35;

  // Score summary card
  const ats     = analyses.ats?.overallScore;
  const grammar = analyses.grammar?.overallScore;
  const match   = analyses.jobMatch?.matchPercentage;
  const skills  = analyses.skills?.matchPercentage;

  if (ats !== undefined || grammar !== undefined || match !== undefined) {
    nl(4);
    setFont('bold', 11, C.heading);
    doc.text('Score Summary', ML, y);
    y += 6;
    drawHR(C.primary, 0.5);

    const scores = [
      { label: 'ATS Score',      value: ats,     suffix: '/100' },
      { label: 'Writing Score',  value: grammar,  suffix: '/100' },
      { label: 'Job Match',      value: match,    suffix: '%' },
      { label: 'Skill Match',    value: skills,   suffix: '%' },
    ].filter(s => s.value !== undefined);

    scores.forEach(s => drawScoreBar(`${s.label}`, s.value));
  }

  // Completed sections list
  nl(6);
  setFont('bold', 11, C.heading);
  doc.text('Sections in this Report', ML, y);
  y += 6;
  drawHR(C.border);

  const sectionMap = [
    { key: 'ats',          label: 'ATS Score Analysis' },
    { key: 'grammar',      label: 'Grammar & Writing Analysis' },
    { key: 'skills',       label: 'Skill Gap Analysis' },
    { key: 'improvements', label: 'Improvement Suggestions' },
    { key: 'jobMatch',     label: 'Job Match Analysis' },
    { key: 'rewrite',      label: 'AI Rewrite Summary' },
    { key: 'coverLetter',  label: 'Generated Cover Letter' },
    { key: 'interview',    label: 'Interview Preparation' },
  ];

  sectionMap.forEach(s => {
    const done = !!analyses[s.key];
    checkPage(7);
    doc.setFillColor(...(done ? C.green : C.muted));
    doc.circle(ML + 2, y - 1, 1.5, 'F');
    setFont(done ? 'bold' : 'normal', 9, done ? C.heading : C.muted);
    doc.text(s.label, ML + 7, y);
    if (done) {
      setFont('bold', 8, C.green);
      doc.text('✓ Included', PW - MR, y, { align: 'right' });
    } else {
      setFont('normal', 8, C.muted);
      doc.text('Not analyzed', PW - MR, y, { align: 'right' });
    }
    y += 6;
  });

  drawPageFooter();

  // ── 1. ATS ANALYSIS ──────────────────────────────────────────
  if (analyses.ats) {
    const d = analyses.ats;
    doc.addPage(); pageNum++; y = MT; drawPageFooter();
    drawSectionHeader('ATS Score Analysis', '🎯');

    drawKeyValue('Overall ATS Score:', `${d.overallScore}/100 — ${scoreLabel(d.overallScore)}`);
    nl(2);

    if (d.sections) {
      drawSubHeader('Section Breakdown');
      Object.entries(d.sections).forEach(([key, sec]) => {
        const label = key.replace(/([A-Z])/g, ' $1').trim();
        drawScoreBar(label, sec.score, sec.maxScore);
        if (sec.details) {
          setFont('italic', 8, C.muted);
          const wrapped = doc.splitTextToSize(sec.details, TW - 10);
          wrapped.forEach(l => { checkPage(4); doc.text(l, ML + 5, y); y += 3.5; });
          nl(1);
        }
      });
    }

    if (d.strengths?.length) {
      drawSubHeader('Strengths');
      d.strengths.forEach(s => drawBullet(s, C.green));
    }
    if (d.weaknesses?.length) {
      drawSubHeader('Weaknesses');
      d.weaknesses.forEach(w => drawBullet(w, C.red));
    }
    if (d.missingElements?.length) {
      drawSubHeader('Missing Elements');
      d.missingElements.forEach(m => drawBullet(m, C.amber));
    }
    if (d.atsKeywords?.length) {
      drawSubHeader('ATS Keywords Detected');
      drawChips(d.atsKeywords, C.primary);
    }
  }

  // ── 2. GRAMMAR ────────────────────────────────────────────────
  if (analyses.grammar) {
    const d = analyses.grammar;
    doc.addPage(); pageNum++; y = MT; drawPageFooter();
    drawSectionHeader('Grammar & Writing Analysis', '✍️');

    drawKeyValue('Writing Score:',        `${d.overallScore}/100`);
    drawKeyValue('Professionalism Score:', `${d.professionalismScore}/100`);
    drawKeyValue('Total Issues Found:',    `${(d.issues || []).length}`);
    nl(2);

    if (d.weakActionVerbs?.length) {
      drawSubHeader('Weak Action Verbs to Replace');
      drawChips(d.weakActionVerbs, C.amber, C.dark);
      nl(2);
    }

    if (d.issues?.length) {
      drawSubHeader('Issues Found');
      d.issues.slice(0, 12).forEach((issue, i) => {
        checkPage(20);
        drawBeforeAfter(issue.original, issue.suggestion);
        if (issue.explanation) {
          setFont('italic', 8, C.muted);
          const w = doc.splitTextToSize(`Why: ${issue.explanation}`, TW);
          w.forEach(l => { checkPage(4); doc.text(l, ML, y); y += 3.5; });
        }
        nl(2);
      });
    }

    if (d.writingTips?.length) {
      drawSubHeader('Writing Tips');
      d.writingTips.forEach(t => drawBullet(t));
    }
  }

  // ── 3. SKILL GAP ─────────────────────────────────────────────
  if (analyses.skills) {
    const d = analyses.skills;
    doc.addPage(); pageNum++; y = MT; drawPageFooter();
    drawSectionHeader('Skill Gap Analysis', '⚡');

    drawKeyValue('Target Role:',     d.jobRole || 'Not specified');
    drawKeyValue('Skill Match:',     `${d.matchPercentage}%`);
    drawKeyValue('Skills Found:',    `${d.foundSkills?.length || 0}`);
    drawKeyValue('Skills Missing:',  `${d.missingSkills?.length || 0}`);
    nl(2);

    if (d.foundSkills?.length) {
      drawSubHeader('Skills You Have ✓');
      drawChips(d.foundSkills, C.green);
    }
    if (d.missingSkills?.length) {
      drawSubHeader('Skills to Learn ✗');
      drawChips(d.missingSkills, C.red);
    }
    if (d.niceToHaveSkills?.length) {
      drawSubHeader('Nice-to-Have Skills');
      drawChips(d.niceToHaveSkills, [99, 102, 241]);
    }
    if (d.skillsByCategory) {
      drawSubHeader('Skills by Category');
      Object.entries(d.skillsByCategory).forEach(([cat, skills]) => {
        checkPage(12);
        setFont('bold', 9, C.heading);
        doc.text(cat.toUpperCase(), ML, y); y += 5;
        if (skills.found?.length) {
          setFont('normal', 8, C.body);
          doc.text('Have: ', ML + 3, y);
          setFont('normal', 8, C.green);
          doc.text(skills.found.join(', '), ML + 14, y);
          y += 4.5;
        }
        if (skills.missing?.length) {
          setFont('normal', 8, C.body);
          doc.text('Missing: ', ML + 3, y);
          setFont('normal', 8, C.red);
          doc.text(skills.missing.join(', '), ML + 18, y);
          y += 4.5;
        }
      });
    }
    if (d.courseSuggestions?.length) {
      drawSubHeader('Recommended Courses');
      d.courseSuggestions.forEach(c => {
        drawBullet(`${c.skill} → "${c.course}" on ${c.platform}`);
      });
    }
  }

  // ── 4. IMPROVEMENTS ──────────────────────────────────────────
  if (analyses.improvements) {
    const d = analyses.improvements;
    doc.addPage(); pageNum++; y = MT; drawPageFooter();
    drawSectionHeader('Improvement Suggestions', '✨');

    drawKeyValue('Total Suggestions:', `${d.totalSuggestions}`);
    nl(2);

    if (d.missingSections?.length) {
      drawSubHeader('Missing Sections');
      drawChips(d.missingSections, C.red);
    }
    if (d.atsKeywordsToAdd?.length) {
      drawSubHeader('ATS Keywords to Add');
      drawChips(d.atsKeywordsToAdd, C.primary);
    }

    ['high', 'medium', 'low'].forEach(priority => {
      const group = (d.prioritySuggestions || []).filter(s => s.priority === priority);
      if (!group.length) return;
      const pColor = priority === 'high' ? C.red : priority === 'medium' ? C.amber : [99, 102, 241];
      drawSubHeader(`${priority.toUpperCase()} Priority (${group.length})`);
      group.forEach(s => {
        checkPage(18);
        setFont('bold', 9, C.heading);
        doc.text(`Section: ${s.section}`, ML, y); y += 4.5;
        setFont('normal', 9, C.red);
        const issueLines = doc.splitTextToSize(`Issue: ${s.issue}`, TW - 5);
        issueLines.forEach(l => { checkPage(4); doc.text(l, ML, y); y += 4; });
        setFont('normal', 9, C.green);
        const fixLines = doc.splitTextToSize(`Fix: ${s.suggestion}`, TW - 5);
        fixLines.forEach(l => { checkPage(4); doc.text(l, ML, y); y += 4; });
        nl(2);
      });
    });

    if (d.bulletPointImprovements?.length) {
      drawSubHeader('Bullet Point Rewrites');
      d.bulletPointImprovements.forEach(b => {
        checkPage(24);
        drawBeforeAfter(b.original, b.improved);
        nl(1);
      });
    }
  }

  // ── 5. JOB MATCH ─────────────────────────────────────────────
  if (analyses.jobMatch) {
    const d = analyses.jobMatch;
    doc.addPage(); pageNum++; y = MT; drawPageFooter();
    drawSectionHeader('Job Match Analysis', '💼');

    drawKeyValue('Match Percentage:',  `${d.matchPercentage}%`);
    drawKeyValue('Match Level:',       d.matchLevel || '—');
    drawKeyValue('Matching Keywords:', `${d.matchingKeywords?.length || 0}`);
    drawKeyValue('Missing Keywords:',  `${d.missingKeywords?.length || 0}`);
    nl(2);

    if (d.experienceMatch) drawScoreBar('Experience Match', d.experienceMatch.score);
    if (d.educationMatch)  drawScoreBar('Education Match',  d.educationMatch.score);
    nl(2);

    if (d.matchingKeywords?.length) {
      drawSubHeader('Matching Keywords ✓');
      drawChips(d.matchingKeywords, C.green);
    }
    if (d.missingKeywords?.length) {
      drawSubHeader('Missing Keywords ✗');
      drawChips(d.missingKeywords, C.red);
    }
    if (d.recommendations?.length) {
      drawSubHeader('Recommendations');
      d.recommendations.forEach(r => drawBullet(r));
    }
    if (d.tailoringTips?.length) {
      drawSubHeader('How to Tailor Your Resume');
      d.tailoringTips.forEach(t => drawBullet(t));
    }
  }

  // ── 6. AI REWRITE ─────────────────────────────────────────────
  if (analyses.rewrite) {
    const d = analyses.rewrite;
    doc.addPage(); pageNum++; y = MT; drawPageFooter();
    drawSectionHeader('AI Rewrite Summary', '🪄');

    if (d.beforeAfterScore) {
      drawKeyValue('Score Before:', `${d.beforeAfterScore.before}/100`);
      drawKeyValue('Score After:',  `${d.beforeAfterScore.after}/100`);
      drawKeyValue('Improvement:',  `+${d.beforeAfterScore.after - d.beforeAfterScore.before} points`);
      nl(2);
    }
    if (d.improvedSummary) {
      drawSubHeader('Rewritten Summary');
      doc.setFillColor(238, 242, 255);
      const summaryLines = doc.splitTextToSize(d.improvedSummary, TW - 6);
      const boxH = summaryLines.length * 4.5 + 6;
      checkPage(boxH + 4);
      doc.roundedRect(ML, y, TW, boxH, 2, 2, 'F');
      setFont('normal', 9, C.heading);
      summaryLines.forEach((l, i) => { doc.text(l, ML + 3, y + 5 + i * 4.5); });
      y += boxH + 4;
    }
    if (d.improvedBulletPoints?.length) {
      drawSubHeader('Rewritten Bullet Points');
      d.improvedBulletPoints.forEach(b => { drawBeforeAfter(b.original, b.improved); nl(1); });
    }
    if (d.keyImprovements?.length) {
      drawSubHeader('Key Improvements Made');
      d.keyImprovements.forEach(imp => drawBullet(imp, C.green));
    }
  }

  // ── 7. COVER LETTER ───────────────────────────────────────────
  if (analyses.coverLetter?.coverLetter) {
    doc.addPage(); pageNum++; y = MT; drawPageFooter();
    drawSectionHeader('Generated Cover Letter', '📧');
    nl(2);
    const clLines = doc.splitTextToSize(analyses.coverLetter.coverLetter, TW);
    clLines.forEach(l => {
      checkPage(5);
      setFont('normal', 10, C.heading);
      doc.text(l, ML, y);
      y += l.trim() === '' ? 3 : 5;
    });
  }

  // ── 8. INTERVIEW ──────────────────────────────────────────────
  if (analyses.interview) {
    const d = analyses.interview;
    doc.addPage(); pageNum++; y = MT; drawPageFooter();
    drawSectionHeader('Interview Preparation', '🎤');

    const sections = [
      { key: 'technicalQuestions',  label: 'Technical Questions',  color: C.primary },
      { key: 'behavioralQuestions', label: 'Behavioral Questions', color: [139, 92, 246] },
      { key: 'projectQuestions',    label: 'Project Questions',    color: C.green },
      { key: 'hrQuestions',         label: 'HR / Culture Questions', color: C.amber },
    ];

    sections.forEach(({ key, label, color }) => {
      const qs = d[key];
      if (!qs?.length) return;
      drawSubHeader(label);
      qs.forEach((q, i) => {
        checkPage(20);
        // Question number badge
        doc.setFillColor(...color);
        doc.roundedRect(ML, y - 4, 6, 5.5, 1, 1, 'F');
        setFont('bold', 8, C.white);
        doc.text(`Q${i + 1}`, ML + 1, y);

        setFont('bold', 9, C.heading);
        const qLines = doc.splitTextToSize(q.question, TW - 10);
        qLines.forEach((l, li) => {
          checkPage(5);
          doc.text(l, ML + 8, y + (li > 0 ? li * 4.5 - 0.5 : 0));
        });
        y += qLines.length * 4.5 + 1;

        const meta = [q.difficulty && `Difficulty: ${q.difficulty}`, q.topic && `Topic: ${q.topic}`, q.competency && `Competency: ${q.competency}`].filter(Boolean);
        if (meta.length) {
          setFont('italic', 8, C.muted);
          doc.text(meta.join('  ·  '), ML + 8, y);
          y += 4;
        }
        if (q.hint) {
          checkPage(8);
          doc.setFillColor(238, 242, 255);
          const hintLines = doc.splitTextToSize(`Hint: ${q.hint}`, TW - 14);
          doc.roundedRect(ML + 8, y - 1, TW - 8, hintLines.length * 4 + 4, 1, 1, 'F');
          setFont('italic', 8, C.primary);
          hintLines.forEach((l, li) => { doc.text(l, ML + 11, y + 2 + li * 4); });
          y += hintLines.length * 4 + 6;
        }
        nl(3);
      });
    });

    if (d.preparationTips?.length) {
      drawSubHeader('Preparation Tips');
      d.preparationTips.forEach(t => drawBullet(t));
    }
  }

  // ── FINAL PAGE footer ─────────────────────────────────────────
  drawPageFooter();
  doc.save(`${baseName}_analysis_report.pdf`);
}

function scoreLabel(score) {
  if (score >= 85) return 'Excellent';
  if (score >= 70) return 'Good';
  if (score >= 50) return 'Needs Work';
  return 'Poor';
}