import { useState } from 'react';
import { motion } from 'framer-motion';
import { Wand2, Sparkles, ArrowRight, TrendingUp, Download, FileText, Loader } from 'lucide-react';
import toast from 'react-hot-toast';
import { rewriteResume } from '../utils/api';
import { useResume } from '../context/ResumeContext';
import { ScoreRing, SectionHeader, CardSkeleton } from '../components/ui/index.jsx';
import NoResume from '../components/ui/NoResume.jsx';

export default function RewritePage() {
  const { state, dispatch } = useResume();
  const [loading, setLoading] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const data = state.analyses.rewrite;

  if (!state.resumeId) return <NoResume />;

  const run = async () => {
    setLoading(true);
    try {
      const res = await rewriteResume(state.resumeId);
      dispatch({ type: 'SET_ANALYSIS', key: 'rewrite', data: res.data });
      toast.success('Resume rewrite complete!');
    } catch (err) { toast.error(err.message); }
    finally { setLoading(false); }
  };

  const buildFullResume = () => {
    const d = data;
    const name = state.fileName?.replace(/\.[^/.]+$/, '') || 'Resume';
    const divider = '─'.repeat(60);
    const lines = [];

    lines.push('═'.repeat(60));
    lines.push(`  ${name.toUpperCase()} — AI REWRITTEN VERSION`);
    lines.push('═'.repeat(60));
    lines.push('');

    if (d.improvedSummary) {
      lines.push('PROFESSIONAL SUMMARY');
      lines.push(divider);
      lines.push(d.improvedSummary);
      lines.push('');
    }

    if (d.improvedBulletPoints?.length) {
      lines.push('EXPERIENCE — REWRITTEN BULLET POINTS');
      lines.push(divider);
      d.improvedBulletPoints.forEach((b, i) => {
        lines.push(`  • ${b.improved}`);
      });
      lines.push('');
    }

    if (d.improvedProjectDescriptions?.length) {
      lines.push('PROJECTS — REWRITTEN DESCRIPTIONS');
      lines.push(divider);
      d.improvedProjectDescriptions.forEach((p) => {
        lines.push(`  • ${p.improved}`);
      });
      lines.push('');
    }

    if (d.keyImprovements?.length) {
      lines.push('KEY IMPROVEMENTS MADE');
      lines.push(divider);
      d.keyImprovements.forEach(imp => lines.push(`  ✓ ${imp}`));
      lines.push('');
    }

    if (d.beforeAfterScore) {
      lines.push('SCORE IMPROVEMENT');
      lines.push(divider);
      lines.push(`  Before: ${d.beforeAfterScore.before}/100`);
      lines.push(`  After:  ${d.beforeAfterScore.after}/100`);
      lines.push(`  Gain:   +${d.beforeAfterScore.after - d.beforeAfterScore.before} points`);
      lines.push('');
    }

    lines.push('═'.repeat(60));
    lines.push('  Generated by AI Resume Analyzer');
    lines.push('═'.repeat(60));

    return lines.join('\n');
  };

  // ADD:
const handleDownload = async () => {
  if (!data) return;
  setDownloading(true);
  try {
    const { jsPDF } = await import('jspdf');
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

    const PW = 210, PH = 297, ML = 15, MR = 15, MT = 20, MB = 15;
    const TW = PW - ML - MR;
    let y = MT;
    let pageNum = 1;

    const C = {
      primary: [79, 70, 229],
      purple:  [124, 58, 237],
      green:   [16, 185, 129],
      red:     [239, 68, 68],
      heading: [30, 41, 59],
      body:    [71, 85, 105],
      muted:   [148, 163, 184],
      white:   [255, 255, 255],
      border:  [226, 232, 240],
      bgBlue:  [238, 242, 255],
      bgGreen: [240, 253, 244],
      bgRed:   [254, 242, 242],
    };

    const baseName = state.fileName?.replace(/\.[^/.]+$/, '') || 'resume';
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    const checkPage = (needed = 10) => {
      if (y + needed > PH - MB) {
        doc.addPage();
        pageNum++;
        y = MT;
        drawFooter();
      }
    };

    const drawFooter = () => {
      doc.setDrawColor(...C.border);
      doc.setLineWidth(0.3);
      doc.line(ML, PH - 10, PW - MR, PH - 10);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(...C.muted);
      doc.text('AI Resume Analyzer — Rewritten Resume', ML, PH - 6);
      doc.text(`Page ${pageNum}`, PW - MR, PH - 6, { align: 'right' });
    };

    const nl = (h = 5) => { y += h; };

    const drawText = (text, x, { size = 10, style = 'normal', color = C.body, maxWidth = TW } = {}) => {
      doc.setFont('helvetica', style);
      doc.setFontSize(size);
      doc.setTextColor(...color);
      const lines = doc.splitTextToSize(text, maxWidth);
      lines.forEach(line => {
        checkPage(size * 0.45 + 2);
        doc.text(line, x, y);
        y += size * 0.45 + 1.8;
      });
    };

    const drawSectionHeader = (title) => {
      checkPage(14);
      nl(4);
      doc.setFillColor(...C.primary);
      doc.roundedRect(ML, y - 5, TW, 10, 2, 2, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(...C.white);
      doc.text(title, ML + 4, y + 1.5);
      y += 8;
      nl(4);
    };

    const drawBeforeAfter = (before, after) => {
      checkPage(28);
      const colW = (TW - 6) / 2;

      // Before
      doc.setFillColor(...C.bgRed);
      doc.setDrawColor(252, 165, 165);
      doc.setLineWidth(0.4);
      const bLines = doc.splitTextToSize(before, colW - 8);
      const boxH = Math.max(18, bLines.length * 4 + 10);
      doc.roundedRect(ML, y, colW, boxH, 2, 2, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      doc.setTextColor(...C.red);
      doc.text('BEFORE', ML + 3, y + 5);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(100, 50, 50);
      bLines.slice(0, 5).forEach((l, i) => doc.text(l, ML + 3, y + 10 + i * 4));

      // After
      const ax = ML + colW + 6;
      doc.setFillColor(...C.bgGreen);
      doc.setDrawColor(134, 239, 172);
      doc.roundedRect(ax, y, colW, boxH, 2, 2, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      doc.setTextColor(...C.green);
      doc.text('AFTER', ax + 3, y + 5);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(20, 80, 50);
      const aLines = doc.splitTextToSize(after, colW - 8);
      aLines.slice(0, 5).forEach((l, i) => doc.text(l, ax + 3, y + 10 + i * 4));

      y += boxH + 5;
    };

    // ── COVER ──────────────────────────────────────────────────
    doc.setFillColor(...C.primary);
    doc.rect(0, 0, PW, 52, 'F');
    doc.setFillColor(...C.purple);
    doc.triangle(PW - 55, 0, PW, 0, PW, 52, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.setTextColor(...C.white);
    doc.text('AI Rewritten Resume', ML, 20);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(199, 210, 254);
    doc.text(baseName, ML, 31);
    doc.text(`Generated: ${date}`, ML, 40);

    y = 64;

    // Score improvement banner
    if (data.beforeAfterScore) {
      const { before, after } = data.beforeAfterScore;
      const gain = after - before;
      doc.setFillColor(...C.bgBlue);
      doc.setDrawColor(...C.primary);
      doc.setLineWidth(0.4);
      doc.roundedRect(ML, y, TW, 22, 3, 3, 'FD');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(...C.heading);
      doc.text('Score Improvement', ML + 4, y + 7);

      // Before score
      doc.setFontSize(18);
      doc.setTextColor(...C.red);
      doc.text(`${before}`, ML + 4, y + 17);
      doc.setFontSize(9);
      doc.setTextColor(...C.muted);
      doc.text('/100 before', ML + 14, y + 17);

      // Arrow
      doc.setFontSize(14);
      doc.setTextColor(...C.primary);
      doc.text('→', ML + 52, y + 17);

      // After score
      doc.setFontSize(18);
      doc.setTextColor(...C.green);
      doc.text(`${after}`, ML + 65, y + 17);
      doc.setFontSize(9);
      doc.setTextColor(...C.muted);
      doc.text('/100 after', ML + 75, y + 17);

      // Gain badge
      doc.setFillColor(...C.green);
      doc.roundedRect(PW - MR - 32, y + 9, 32, 8, 2, 2, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(...C.white);
      doc.text(`+${gain} pts improvement`, PW - MR - 16, y + 14.5, { align: 'center' });

      y += 28;
    }

    // ── IMPROVED SUMMARY ───────────────────────────────────────
    if (data.improvedSummary) {
      drawSectionHeader('✦  Professional Summary');

      doc.setFillColor(...C.bgBlue);
      doc.setDrawColor(...C.primary);
      doc.setLineWidth(0.3);
      const sumLines = doc.splitTextToSize(data.improvedSummary, TW - 8);
      const sumH = sumLines.length * 5 + 8;
      checkPage(sumH + 4);
      doc.roundedRect(ML, y, TW, sumH, 3, 3, 'FD');
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9.5);
      doc.setTextColor(...C.heading);
      sumLines.forEach((l, i) => doc.text(l, ML + 4, y + 7 + i * 5));
      y += sumH + 6;
    }

    // ── BULLET POINTS ──────────────────────────────────────────
    if (data.improvedBulletPoints?.length) {
      drawSectionHeader('✦  Rewritten Experience Bullet Points');
      data.improvedBulletPoints.forEach((b, i) => {
        checkPage(32);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(...C.muted);
        doc.text(`Bullet ${i + 1}`, ML, y);
        y += 4;
        drawBeforeAfter(b.original, b.improved);
      });
    }

    // ── PROJECT DESCRIPTIONS ───────────────────────────────────
    if (data.improvedProjectDescriptions?.length) {
      drawSectionHeader('✦  Rewritten Project Descriptions');
      data.improvedProjectDescriptions.forEach((p, i) => {
        checkPage(32);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(...C.muted);
        doc.text(`Project ${i + 1}`, ML, y);
        y += 4;
        drawBeforeAfter(p.original, p.improved);
      });
    }

    // ── KEY IMPROVEMENTS ───────────────────────────────────────
    if (data.keyImprovements?.length) {
      drawSectionHeader('✦  Key Improvements Made');
      data.keyImprovements.forEach(imp => {
        checkPage(8);
        doc.setFillColor(...C.green);
        doc.circle(ML + 1.5, y - 1, 1.2, 'F');
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9.5);
        doc.setTextColor(...C.heading);
        const lines = doc.splitTextToSize(imp, TW - 8);
        lines.forEach((l, i) => {
          checkPage(5);
          doc.text(l, ML + 6, y + (i > 0 ? i * 4.5 - 0.5 : 0));
        });
        y += lines.length * 4.5 + 2;
      });
    }

    drawFooter();
    doc.save(`${baseName}_rewritten_resume.pdf`);
    toast.success('PDF downloaded!');
  } catch (err) {
    console.error(err);
    toast.error('Failed to generate PDF');
  } finally {
    setDownloading(false);
  }
};

  return (
    <div className="max-w-3xl mx-auto">
      <SectionHeader icon={Wand2} title="AI Resume Rewriter"
        description="Transform weak bullet points and descriptions into compelling achievements"
        action={
          <div className="flex gap-2">
            {data && (
              <button onClick={handleDownload} className="btn-secondary">
                <Download size={14} /> Download
              </button>
            )}
            <button onClick={run} disabled={loading} className="btn-primary">
              {loading ? <><div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />Rewriting...</> : <><Wand2 size={14} />Rewrite Resume</>}
            </button>
          </div>
        }
      />

      {loading && (
        <div className="space-y-4">
          <div className="card p-6 text-center">
            <div className="w-12 h-12 rounded-2xl bg-primary-50 dark:bg-primary-900/20 flex items-center justify-center mx-auto mb-3">
              <Wand2 size={22} className="text-primary-600 dark:text-primary-400 animate-pulse" />
            </div>
            <p className="font-semibold text-slate-700 dark:text-slate-300">AI is rewriting your resume...</p>
            <p className="text-sm text-slate-500 mt-1">This may take 15–30 seconds</p>
          </div>
          <CardSkeleton /><CardSkeleton />
        </div>
      )}

      {!loading && !data && (
        <div className="card p-12 text-center">
          <Wand2 size={32} className="text-slate-400 mx-auto mb-4" />
          <p className="font-semibold text-slate-700 dark:text-slate-300 mb-2">AI Resume Rewriter</p>
          <p className="text-sm text-slate-500 mb-5 max-w-md mx-auto">
            Our AI will rewrite your bullet points with stronger action verbs, quantified achievements, and professional language.
          </p>
          <button onClick={run} className="btn-primary mx-auto"><Wand2 size={14} />Rewrite My Resume</button>
        </div>
      )}

      {!loading && data && (
        <motion.div className="space-y-5" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
          {/* Score improvement */}
          {data.beforeAfterScore && (
            <div className="card p-6 flex flex-col sm:flex-row items-center gap-8">
              <div className="flex items-center gap-6">
                <div className="text-center">
                  <ScoreRing score={data.beforeAfterScore.before} size={100} label="Before" color="#ef4444" />
                </div>
                <TrendingUp size={28} className="text-emerald-500 flex-shrink-0" />
                <div className="text-center">
                  <ScoreRing score={data.beforeAfterScore.after} size={100} label="After" color="#10b981" />
                </div>
              </div>
              <div className="flex-1">
                <p className="text-2xl font-bold text-emerald-600 dark:text-emerald-400">
                  +{data.beforeAfterScore.after - data.beforeAfterScore.before} points improvement
                </p>
                <p className="text-slate-500 text-sm mt-1">Your rewritten resume is significantly stronger</p>
              </div>
            </div>
          )}

          {/* Improved summary */}
          {data.improvedSummary && (
            <div className="card p-5">
              <p className="font-semibold text-slate-900 dark:text-white mb-3 flex items-center gap-2">
                <Sparkles size={14} className="text-primary-500" /> Improved Summary / Objective
              </p>
              <div className="bg-primary-50 dark:bg-primary-900/20 border border-primary-200 dark:border-primary-800 rounded-xl p-4">
                <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{data.improvedSummary}</p>
              </div>
            </div>
          )}

          {/* Bullet point rewrites */}
          {data.improvedBulletPoints?.length > 0 && (
            <div className="card p-5">
              <p className="font-semibold text-slate-900 dark:text-white mb-4">Rewritten Bullet Points</p>
              <div className="space-y-5">
                {data.improvedBulletPoints.map((b, i) => (
                  <div key={i} className="space-y-2">
                    <div className="bg-red-50 dark:bg-red-900/10 border border-red-200 dark:border-red-900/40 rounded-xl p-3.5">
                      <p className="text-[10px] font-bold text-red-400 uppercase tracking-wider mb-1.5">Before</p>
                      <p className="text-sm text-slate-600 dark:text-slate-400">{b.original}</p>
                    </div>
                    <div className="flex items-center justify-center">
                      <ArrowRight size={16} className="text-primary-400 rotate-90" />
                    </div>
                    <div className="bg-emerald-50 dark:bg-emerald-900/10 border border-emerald-200 dark:border-emerald-900/40 rounded-xl p-3.5">
                      <p className="text-[10px] font-bold text-emerald-500 uppercase tracking-wider mb-1.5">After</p>
                      <p className="text-sm text-slate-800 dark:text-slate-200 font-medium">{b.improved}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Project descriptions */}
          {data.improvedProjectDescriptions?.length > 0 && (
            <div className="card p-5">
              <p className="font-semibold text-slate-900 dark:text-white mb-4">Improved Project Descriptions</p>
              <div className="space-y-4">
                {data.improvedProjectDescriptions.map((p, i) => (
                  <div key={i} className="space-y-2">
                    <div className="bg-slate-50 dark:bg-slate-800 rounded-xl p-3.5">
                      <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">Original</p>
                      <p className="text-sm text-slate-600 dark:text-slate-400">{p.original}</p>
                    </div>
                    <div className="bg-primary-50 dark:bg-primary-900/20 border border-primary-200 dark:border-primary-800 rounded-xl p-3.5">
                      <p className="text-[10px] font-bold text-primary-500 uppercase tracking-wider mb-1">Improved</p>
                      <p className="text-sm text-slate-800 dark:text-slate-200">{p.improved}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Key improvements */}
          {data.keyImprovements?.length > 0 && (
            <div className="card p-5">
              <p className="font-semibold text-slate-900 dark:text-white mb-3">Key Improvements Made</p>
              <ul className="space-y-2">
                {data.keyImprovements.map(imp => (
                  <li key={imp} className="text-sm text-slate-600 dark:text-slate-400 flex items-start gap-2">
                    <Sparkles size={12} className="text-emerald-500 mt-0.5 flex-shrink-0" />{imp}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Download full resume banner */}
          <div className="card p-6 bg-gradient-to-br from-primary-600 to-purple-600 border-0 flex flex-col sm:flex-row items-center gap-4">
            <div className="w-12 h-12 rounded-xl bg-white/20 flex items-center justify-center flex-shrink-0">
              <FileText size={24} className="text-white" />
            </div>
            <div className="flex-1 text-center sm:text-left">
              <p className="font-bold text-white text-base">Download Your Rewritten Resume</p>
              <p className="text-primary-100 text-sm mt-0.5">
                Get the full rewritten version as a clean text file — ready to paste into any editor.
              </p>
            </div>
            <button
              onClick={handleDownload}
              className="flex-shrink-0 inline-flex items-center gap-2 bg-white text-primary-700 font-semibold px-5 py-2.5 rounded-xl hover:bg-primary-50 transition-colors text-sm"
            >
              <Download size={15} /> Download .txt
            </button>
          </div>
        </motion.div>
      )}
    </div>
  );
}
